### ISSUE TITLE
Change colour of more locations in search results

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#12] opened 2018-10-01 12:00 UTC
(use yellowy-orange we already have elsewhere)

**Comment by Mike-Heneghan** [comment] 2018-10-01 12:11
Colour: #f49c27

**Comment by digitalWestie** [comment] 2018-10-02 10:33
It should be defined as a variable somewhere, so if you can stick to that our stylesheets will be easier to maintain.

**Comment by Mike-Heneghan** [comment] 2018-10-12 09:50
Updated my forks master and checked out a branch for the enhancement ```enhance/locations-colour```. 

- [ ] Find the colour to use (Colour: #f49c27)
- [ ] Find the variable in the stylesheets.
- [ ] Update with the new colour.
- [ ] Visually check front-end to ensure it has worked as intended

**Comment by Mike-Heneghan** [comment] 2018-10-12 14:35
<a class="more-link">More Locations</a>

Bit of trouble generating the static files from the scss files using gulp although completed now. 

Edited the ```src/scss/partials/results.scss``` file to overwrite the colour to #f49c27.

**Comment by Mike-Heneghan** [comment] 2018-10-30 14:48
Manually merged

**Closed by Mike-Heneghan** 2018-10-30 14:48 UTC
Labels: Fixed (to be reviewed)
