### ISSUE TITLE
Username misalignment

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#5] opened 2018-10-01 10:00 UTC
See: https://github.com/aliss/ALISS/issues/10

**Comment by Mike-Heneghan** [comment] 2018-10-15 10:35
Based on this screenshot the ```Login``` and ```Logout``` are at the same level which is slightly about the ```Give Feedback``` baseline:
![image](https://user-images.githubusercontent.com/36415632/46945804-c29ecd80-d06d-11e8-89a8-aa3f563c7aea.png)

Once logged in it would appear the username ```Mike```and ```Give Feedback``` are on the correct level and the ```Logout``` is in the same poisition i.e. too high. 
![image](https://user-images.githubusercontent.com/36415632/46945812-c6325480-d06d-11e8-82a3-d5cde4cd374e.png)

**Comment by Mike-Heneghan** [comment] 2018-10-15 13:47
Issue is with the ul although can't find the reason it needs to be a further ```0.1em``` from the top.

**Comment by Mike-Heneghan** [comment] 2018-10-15 14:31
After lots of hunting for the cause and solution the best option I could find was that as the font-weights are dissimilar the spacing is also different therefore a different ```top:``` attribute is required.

Using 

```
ul {
		position: relative;
		top: (0.1em + $top-hat-spacing);
```
Improved the format as seen below:

<img width="479" alt="screen shot 2018-10-15 at 15 27 47" src="https://user-images.githubusercontent.com/36415632/46957267-1bcb2900-d08f-11e8-8dbc-b599ec9db73b.png">

Although this doesn't seem like a particulalry maintainable solution.

**Comment by Mike-Heneghan** [comment] 2018-10-31 14:43
Merged Manually

**Closed by Mike-Heneghan** 2018-10-31 14:43 UTC
Labels: Fixed (to be reviewed)
